namespace GameProject
{
    public static class Program
    {
        // autogenerated by MonoGame - instantiates KProject class
        static void Main()
        {
            using (var game = new KProject())
            {
                game.Run();
            }
        }
    }
}
